# Generated by Django 3.2.3 on 2021-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='name',
            field=models.CharField(default='empty', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
