# Generated by Django 3.2.3 on 2021-06-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210609_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
