# Generated by Django 3.2.3 on 2021-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='photo',
            field=models.ImageField(default='blank', height_field=100, upload_to='', width_field=75),
            preserve_default=False,
        ),
    ]
