# Generated by Django 3.2.3 on 2021-06-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listings_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='photo',
        ),
    ]
