# Generated by Django 3.2.3 on 2021-06-09 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_listings_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
