# Generated by Django 3.2.3 on 2021-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_listings_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
