# Generated by Django 3.2.3 on 2021-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listings_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='photo',
            field=models.ImageField(default='No photo', height_field=100, upload_to='auctions/images', width_field=75),
            preserve_default=False,
        ),
    ]
