# Generated by Django 3.2.3 on 2021-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210609_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='height',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='width',
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='photo',
            field=models.ImageField(upload_to='auctions/images'),
        ),
    ]
