# Generated by Django 3.2.3 on 2021-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210616_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category',
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Other', 'Other'), (None, 'None')], max_length=64),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='watchlist_listings', to='auctions.Auction_Listing'),
        ),
    ]
