# Generated by Django 3.2.3 on 2021-06-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20210624_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='current_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid_of_item', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/images'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist_listings', to='auctions.Auction_Listing'),
        ),
    ]
