# Generated by Django 3.2.3 on 2021-06-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auto_20210624_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.ForeignKey(blank=True, default='None', on_delete=django.db.models.deletion.CASCADE, related_name='category_of_item', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='watchlist_listings', to='auctions.Auction_Listing'),
        ),
    ]
